apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o09d0l06b-java-springboot
  janus-idp.io/tekton: o09d0l06b-java-springboot
  backstage.io/kubernetes-id: o09d0l06b-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o09d0l06b-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
